name: Flake8 annotation
description: Run flake8 and annotate the results
author: multani

branding:
  icon: check-circle
  color: yellow

inputs:
  check-name:
    description: |
      The name of the check to add annotations to.

      Generally the same as the job that uses this action.
    required: true

  command:
    description: The command to run to execute Flake8.
    default: flake8 --exit-zero
    required: false

  working-directory:
    description: The directory to execute Flake8 from.
    required: false

runs:
  using: node12
  main: dist/index.js
